name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install package in editable mode with dependencies
          pip install -e .
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Check import
        run: |
          python -c "from faff_cli.main import cli; print('✓ Import successful')"

  lint:
    name: Lint and format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy

      - name: Check formatting with black
        run: |
          black --check src/ tests/
        continue-on-error: true  # Don't fail initially

      - name: Check import sorting
        run: |
          isort --check-only src/ tests/
        continue-on-error: true  # Don't fail initially

      - name: Type check with mypy
        run: |
          mypy src/ --ignore-missing-imports
        continue-on-error: true  # Don't fail on type errors initially
